### ISSUE TITLE
GFT werkt niet meer voor omrin

### ISSUE THREAD

**Issue by matsjoe** [heyajohnny/afvalinfo#126]
Krijg momenteel de huidige error. 

2020-10-01 16:29:17 WARNING (SyncWorker_39) [custom_components.afvalinfo.const.const] Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'gft' is not supported on your location
2020-10-01 16:29:17 WARNING (SyncWorker_39) [custom_components.afvalinfo.const.const] Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'gft' is not supported on your location
2020-10-01 16:29:17 WARNING (SyncWorker_39) [custom_components.afvalinfo.const.const] Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'gft' is not supported on your location
2020-10-01 16:29:17 WARNING (SyncWorker_39) [custom_components.afvalinfo.const.const] Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'gft' is not supported on your location
2020-10-01 16:29:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 472, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 332, in update
    self.data = OmrinAfval().get_data(
  File "/config/custom_components/afvalinfo/location/omrin.py", line 173, in get_data
    if len(tuinafval) != 0 and len(extratuinafval) == 0:
TypeError: object of type 'NoneType' has no len()

Gebruik hem met Omrin voor in leeuwarden.

**Comment by heyajohnny** [comment]
Werkt prima met de adresgegevens 8921js 12 leeuwarden.
![image](https://user-images.githubusercontent.com/20553716/95679196-71c8fd80-0bd1-11eb-99fa-b6fbbb741e43.png)

**Comment by heyajohnny** [comment]
Laat even weten of het probleem verholpen is, anders sluit ik over enkele dagen dit issue

**Comment by matsjoe** [comment]
Werkt hier indd ook weer was wss een hick up
