### ISSUE TITLE
Waste collector "cyclus (required)" not found!

### ISSUE THREAD

**Issue by hiddit** [heyajohnny/afvalinfo#138]
```
Logger: homeassistant.helpers.entity
Source: custom_components/afvalbeheer/sensor.py:447
First occurred: 9:40:45 (19 occurrences)
Last logged: 9:49:45

Update for sensor.cyclus_required_at_least_1_required_restafval_gft_papier_pmd fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1374, in update
    collection = self.data.collections.get_first_upcoming_by_type(self.waste_type)
  File "/config/custom_components/afvalbeheer/sensor.py", line 447, in collections
    return self.collector.collections
AttributeError: 'NoneType' object has no attribute 'collections'
```

**Comment by hiddit** [comment]
never mind
