### ISSUE TITLE
Error fetching Circulus-Berkel when Papier is removed as resource

### ISSUE THREAD

**Issue by MerlijnKerklaan** [heyajohnny/afvalinfo#142]
Hi there, thanks for the wonderful and complete afvalinfo home assistant component!

I've got a small issue when removing 'Papier' as a resource, the following error occurs;

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 481, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 246, in update
    self.data = CirculusBerkelAfval().get_data(
  File "/config/custom_components/afvalinfo/location/circulusberkel.py", line 58, in get_data
    if len(waste_dict["papier"]) == 0:
KeyError: 'papier'

My current config (for the error to appear) is:

  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - trash_type_today
      - trash_type_tomorrow
    location: Doesburg
    postcode: 6981DA
    streetnumber: 19
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365

As a workaround I added paper to the resources but maybe something to fix when you have the time...

Thanks again!

**Comment by heyajohnny** [comment]
Thnx!
It was a stupid, lazy ass bug :( I've just pushed a fix and it should work now, without 'papier'
