### ISSUE TITLE
Westland afvalkalender fails

### ISSUE THREAD

**Issue by steef84** [heyajohnny/afvalinfo#28]
Errors in log 3 for all sensors

`Update for sensor.afvalinfo_restafval fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 264, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 222, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/westland.py", line 63, in get_data
    html = r.json()["html"]
KeyError: 'html'`

`Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 264, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 222, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/westland.py", line 63, in get_data
    html = r.json()["html"]
KeyError: 'html'`

`Update for sensor.afvalinfo_oud_papier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 264, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 222, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/westland.py", line 63, in get_data
    html = r.json()["html"]
KeyError: 'html'`

**Comment by heyajohnny** [comment]
It works just fine when I'm using these parameters:
![image](https://user-images.githubusercontent.com/20553716/76130067-ae17f800-6009-11ea-8dfb-ef8a49cc44ee.png)

Have you tried using the postcode and huisnummer on this site: https://www.gemeentewestland.nl/afval/huisvuil.html

If you don't get any result in there, you won't get any result in afvalinfo.

I can't help you any further if I don't know the postcode and huisnummer you are using...

**Comment by steef84** [comment]
Thanks I using 2671XE 10 Naaldwijk. You made it work once for me here https://github.com/heyajohnny/afvalinfo/issues/6

**Comment by heyajohnny** [comment]
The 3 available resources give data back as expected.
![image](https://user-images.githubusercontent.com/20553716/76147122-51641e00-6099-11ea-9f8d-944e03fbdbed.png)

I know that the certificate of westland is not valid, but in my code, I'm ignoring it so that I can retrieve data even with an invalid certificate.
Maybe you've changed something in your home assistant that's blocking the invalid certificate or something. That's the only thing I can think of...

**Comment by steef84** [comment]
Don't know what I did wrong, but reapplied the plugins and settings, now working again! Thank for the advices!

**Comment by heyajohnny** [comment]
Oke, good to hear it's working again.
