### ISSUE TITLE
"Update for sensor.afvalinfo_xxx fails" in westerkwartier.py

### ISSUE THREAD

**Issue by jov58** [heyajohnny/afvalinfo#35]
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/afvalinfo/sensor.py", line 250, in update
    self.data.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/afvalinfo/sensor.py", line 211, in update
    self.city, self.postcode, self.street_number
  File "/home/homeassistant/.homeassistant/custom_components/afvalinfo/location/westerkwartier.py", line 26, in get_data
    items = r.json()["items"]
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Ik heb een plaatsnaam, postcode en huisnummer uit een ander gebied (ROVA) ingevuld dan westerkwartier.

**Comment by heyajohnny** [comment]
Dit is het probleem met Den Ham uit Westerkwartier. Door de fix die ik zojuist heb doorgevoerd zou deze foutmelding niet meer moeten verschijnen.
