### ISSUE TITLE
Sensor not updating

### ISSUE THREAD

**Issue by martijndemulder** [heyajohnny/afvalinfo#44]
Hey Johnny,

Finally had the time (and courage) to update, but now the sensors aren't updating anymore.
In the logging I see the following:
"Updating afvalinfo sensor took longer than the scheduled update interval 0:00:30" and none of the sensors are updating.
All of the sensors show "unknown" as their state.

My configuration can be found below:
`  - platform: afvalinfo
    resources:
      - pbd
      - gft
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    city: helmond
    postcode: 1234AB <--Changed for privacy purposes
    streetnumber: 50 <--Changed for privacy purposes
    dateformat: '%d-%m-%Y'
    timespanindays: 365`

Maybe I'm doing something wrong? I hardly doubt that since it was working until the update.
If you need more info, please ask!

**Comment by martijndemulder** [comment]
My Logbook details:

> Logboekdetails ( ERROR )
Logger: homeassistant.helpers.entity
Source: custom_components/afvalinfo/location/deafvalapp.py:53
First occurred: 19:56:08 (4 occurrences)
Last logged: 20:01:39

Update for sensor.afvalinfo_oud_papier fails
Update for sensor.afvalinfo_pbd fails
Update for sensor.afvalinfo_restafval fails
Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 267, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 140, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/deafvalapp.py", line 53, in get_data
    res = op.open(url)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1322, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by martijndemulder** [comment]
Never mind....apparently the site was down at exactly the moment I was tinkering with this.
Sorry!
