### ISSUE TITLE
toevoegen Westland

### ISSUE THREAD

**Issue by steef84** [heyajohnny/afvalinfo#6]
Is het mogelijk de Westland afval kalender toe te voegen? Domoticz werkend lua script hier te vinden: https://github.com/jvanderzande/GarbageCalendar, weet niet of dat de boel makkelijker maakt. Zou in ieder geval top zijn

**Comment by heyajohnny** [comment]
Ik heb al wat voorbereidingen gemaakt om Westland toe te voegen.
Waarschijnlijk ergens volgende week moet de functionaliteit er wel inzitten.

**Comment by heyajohnny** [comment]
Ik had vandaag nog even tijd. Westland is toegevoegd. Veel plezier :)

**Comment by steef84** [comment]
Nice on, snel geprobeerd te gebruiken, maar een errrr
```
sensor:
  - platform: afvalinfo
    resources:
      - restafval
    city: naaldwijk
    postcode: 2671XE
    streetnumber: 1
    dateformat: '%d-%m-%Y'
    timespanindays: 365
```
```

Update for sensor.afvalinfo_restafval fails
14:35 custom_components/afvalinfo/location/westland.py (ERROR)
```

```
Fri Feb 14 2020 14:35:05 GMT+0100 (CET)

Update for sensor.afvalinfo_restafval fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 292, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 251, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/westland.py", line 64, in get_data
    waste_dict["papier"] = self.get_date_from_afvaltype(html, "soort-papier")
  File "/config/custom_components/afvalinfo/location/westland.py", line 30, in get_date_from_afvaltype
    month = MONTH_TO_NUMBER[date.split(" ")[2]]
KeyError: '5'
```

**Comment by heyajohnny** [comment]
Zojuist een bug fix doorgevoerd. Er kunnen blijkbaar ook lege waardes voorkomen... Daar had ik geen rekening mee gehouden.
Als het goed is moet het nu werken.

**Comment by steef84** [comment]
Cool, restafval en gft geven nu een datum, papier blijft op datum onbekend staan. In de log zie ik niet zo snel een fout

**Comment by heyajohnny** [comment]
Vreemd... Ik zal er volgende week naar kijken.

**Comment by heyajohnny** [comment]
Het zou nu moeten werken :)
