### ISSUE TITLE
Meerlanden werkt niet meer

### ISSUE THREAD

**Issue by rossiexp** [heyajohnny/afvalinfo#73]
Helaas werkt De Meerlanden niet meer.

Update for sensor.afvalinfo_restafval fails
Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 327, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 194, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/meerlanden.py", line 40, in get_data
    uniqueId = r.json()["dataList"][0]["UniqueId"]
TypeError: 'NoneType' object is not subscriptable

**Comment by rossiexp** [comment]
Het blijkt een fout op de meerlanden site te zijn, hij herkent een geldig postcode / huisnummer niet meer.

**Comment by heyajohnny** [comment]
Ik zie op de site van Meerlanden inderdaad hetzelfde probleem met enkele willekeurige adressen die ik heb geprobeerd. Ik kan hier helaas niets aan doen :(

**Comment by heyajohnny** [comment]
Meerlanden lijkt weer te werken...

**Comment by heyajohnny** [comment]
Ik sluit deze issue. Volgens mij werkt alles weer. Mocht het niet zo zijn, dan hoor ik dat graag
