### ISSUE TITLE
Omrin probleem

### ISSUE THREAD

**Issue by 0000vt** [heyajohnny/afvalinfo#74]
Goedendag,

Ik krijg in mijn integratie geen adres binnen het omrin domein werkend. Met wat tests bij Sudwest fryslan werkt het wel. De sensor blijft bij een adres van omrin op 'unknown' staan. Ik heb door de code gekeken of ik het probleem kan opsporen maar dat lukt niet zomaar. Is er wellicht een debug log of kan je het zelf testen?

Bedankt

**Comment by 0000vt** [comment]
Ah, een log gevonden:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 427, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 320, in update
    self.city, self.postcode, self.street_number
  File "/config/custom_components/afvalinfo/location/omrin.py", line 86, in get_data
    omrinDataGroups = script[script.index("{"):]
ValueError: substring not found`

**Comment by heyajohnny** [comment]
Ik heb zojuist een fix doorgevoerd. Zou je nog even kunnen laten weten of het bij jou weer werkt?

**Comment by 0000vt** [comment]
Bedankt voor de fix! Het is inderdaad nu opgelost.

**Comment by 0000vt** [comment]
Echter is er nog een ander probleem bij Omrin. 

"
![image](https://user-images.githubusercontent.com/35564839/80482833-3a350480-8955-11ea-9f91-db6181b879e3.png)
"
Is het wellicht hoofdletter gevoelig? Op de omrin kalender is het "Oud Papier en karton"

**Comment by heyajohnny** [comment]
Nu is het niet meer hoofdletter gevoelig.
Je zou nog steeds een warning kunnen krijgen, aangezien hij verschillende teksten probeerd, maar je zou wel altijd een resultaat moeten krijgen

**Comment by 0000vt** [comment]
Ja super, is nu opgelost. Met de vorige versie kreeg ik 'unknown', maar dat is nu opgelost.
